name: check pull request

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

env:
  PACKAGES: make lua5.1 lua-filesystem lua-check lua-busted

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install Packages
      run: sudo apt-get install $PACKAGES

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Run checks
      run: make check
